name: ROS Pre-Release Test
on: [push]

env:
  CONFIG_URL: https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml
  REPO_NAME: rosflight

jobs:
  prerelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosdistro: [kinetic, melodic]
        include:
          - rosdistro: kinetic
            os_name: ubuntu
            os_codename: xenial
            arch: amd64
          - rosdistro: melodic
            os_name: ubuntu
            os_codename: bionic
            arch: amd64
      fail-fast: false
    steps:
      - name: Install ROS Buildfarm
        run: |
          pip install ros_buildfarm
      - uses: actions/checkout@v2
        with:
          path: ws/src/${{ github.repository }}
      - name: Generate devel script
        run: |
          generate_devel_script.py $CONFIG_URL ${{ matrix.rosdistro }} default $REPO_NAME ${{ matrix.os_name }} ${{ matrix.os_codename }} ${{ matrix.arch }} > devel_job.sh
      - name: Run devel script
        run: |
          sh devel_job.sh -y
